export const GET_ERRORS = "GET_ERRORS";

export const SET_CURRENT_USER = "SET_CURRENT_USER";

export const GET_CURRENT_USER = "GET_CURRENT_USER";
export const GET_CURRENT_USER_SUCCESS = "GET_CURRENT_USER_SUCCESS";
export const GET_CURRENT_USER_FAILURE = "GET_CURRENT_USER_FAILURE";

export const GET_TOP_USERS_START = "GET_TOP_USERS_INIT";
export const GET_TOP_USERS_SUCCESS = "GET_TOP_USERS_SUCCESS";
export const GET_TOP_USERS_FAILURE = "GET_TOP_USERS_FAILURE";

export const GET_NEW_USERS_START = "GET_NEW_USERS_INIT";
export const GET_NEW_USERS_SUCCESS = "GET_NEW_USERS_SUCCESS";
export const GET_NEW_USERS_FAILURE = "GET_NEW_USERS_FAILURE";

export const GET_POSTS_START = "GET_POSTS_START";
export const GET_POSTS_SUCCESS = "GET_POSTS_SUCCESS";
export const GET_POSTS_FAILURE = "GET_POSTS_FAILURE";

export const CREATE_POST_SUCCESS = "CREATE_POST_SUCCESS";
export const CREATE_POST_FAILURE = "CREATE_POST_FAILURE";

export const CLEAR_USER = "CLEAR_USER";

export const GET_USER_PAGE_START = "GET_USER_PAGE_START";
export const GET_USER_PAGE_SUCCESS = "GET_USER_PAGE_SUCCESS";
export const GET_USER_PAGE_FAILURE = "GET_USER_PAGE_FAILURE";

export const GET_USER_PAGE_POSTS_START = "GET_USER_PAGE_POSTS_START";
export const GET_USER_PAGE_POSTS_SUCCESS = "GET_USER_PAGE_POSTS_SUCCESS";
export const GET_USER_PAGE_POSTS_FAILURE = "GET_USER_PAGE_POSTS_FAILURE";

export const LIKE_POST_SUCCESS = "LIKE_POST_SUCCESS";
export const LIKE_POST_FAILURE = "LIKE_POST_FAILURE";

export const UNLIKE_POST_FAILURE = "UNLIKE_POST_FAILURE";

export const CREATE_COMMENT_SUCCESS = "CREATE_COMMENT_SUCCESS";
export const CREATE_COMMENT_FAILURE = "CREATE_COMMENT_FAILURE";