export const GET_ERRORS = "GET_ERRORS";

export const SET_CURRENT_USER = "SET_CURRENT_USER";

export const GET_CURRENT_USER = "GET_CURRENT_USER";
export const GET_CURRENT_USER_SUCCESS = "GET_CURRENT_USER_SUCCESS";
export const GET_CURRENT_USER_FAILURE = "GET_CURRENT_USER_FAILURE";

export const GET_TOP_USERS_START = "GET_TOP_USERS_INIT";
export const GET_TOP_USERS_SUCCESS = "GET_TOP_USERS_SUCCESS";
export const GET_TOP_USERS_FAILURE = "GET_TOP_USERS_FAILURE";

export const GET_NEW_USERS_START = "GET_NEW_USERS_INIT";
export const GET_NEW_USERS_SUCCESS = "GET_NEW_USERS_SUCCESS";
export const GET_NEW_USERS_FAILURE = "GET_NEW_USERS_FAILURE";